# https://terraform-docs.io/user-guide/configuration/

formatter: "md"

settings:
  hide-empty: true

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
